# config/__init__.py
"""
Configuration 모듈
"""

from .constants import (
    VISIT_TIMES,
    LUNCH_START_RANGE,
    DINNER_START_RANGE,
    THEME_WEIGHTS,
    # 5-Phase 파이프라인 신규 상수
    HOTEL_CATEGORIES,
    BUDGET_MIN_RATING,
    CANDIDATE_POOL_RATIO,
    HOTEL_ANCHOR_TIME_THRESHOLD,
    PACE_MAX_PLACES,
    COMPANION_STAY_MULTIPLIER,
    AIRPORT_COORDS,
    # Phase 5: 타임박싱 Cut-off 기준
    CUTOFF_HOUR,
    TRANSIT_LAST_HOUR,
    # 점수 설계 상수 (베이지안 + 별점 분포)
    REVIEW_COUNT_BONUS,
    BAYESIAN_C,
    BAYESIAN_GLOBAL_AVG,
    BAYESIAN_SCORE_MULTIPLIER,
    RATING_DIST_POSITIVE_TIERS,
    RATING_DIST_NEGATIVE_TIERS,
    DATA_FRESHNESS_PENALTY,
    # 영업 상태 경고 기준
    PLACE_STALE_WARNING_DAYS,
    PLACE_STALE_HIGH_RISK_DAYS,
    # 세부 카테고리 분류 체계
    SUB_CATEGORY_MAP,
    CATEGORY_KEYWORD_MAP,
    ADULT_ONLY_KEYWORDS,
)

from .settings import (
    KOREAN_CITIES,
    DEFAULT_MIN_RATING,
    DEFAULT_MIN_HOTEL_RATING,
    DEFAULT_SIGHTS_PER_DAY,
    DEFAULT_FOODS_PER_DAY,
    DEFAULT_CAFES_PER_DAY
)

__all__ = [
    'VISIT_TIMES',
    'LUNCH_START_RANGE',
    'DINNER_START_RANGE',
    'THEME_WEIGHTS',
    'HOTEL_CATEGORIES',
    'BUDGET_MIN_RATING',
    'CANDIDATE_POOL_RATIO',
    'HOTEL_ANCHOR_TIME_THRESHOLD',
    'PACE_MAX_PLACES',
    'COMPANION_STAY_MULTIPLIER',
    'AIRPORT_COORDS',
    'CUTOFF_HOUR',
    'TRANSIT_LAST_HOUR',
    'REVIEW_COUNT_BONUS',
    'BAYESIAN_C',
    'BAYESIAN_GLOBAL_AVG',
    'BAYESIAN_SCORE_MULTIPLIER',
    'RATING_DIST_POSITIVE_TIERS',
    'RATING_DIST_NEGATIVE_TIERS',
    'DATA_FRESHNESS_PENALTY',
    'PLACE_STALE_WARNING_DAYS',
    'PLACE_STALE_HIGH_RISK_DAYS',
    'SUB_CATEGORY_MAP',
    'CATEGORY_KEYWORD_MAP',
    'ADULT_ONLY_KEYWORDS',
    'KOREAN_CITIES',
    'DEFAULT_MIN_RATING',
    'DEFAULT_MIN_HOTEL_RATING',
    'DEFAULT_SIGHTS_PER_DAY',
    'DEFAULT_FOODS_PER_DAY',
    'DEFAULT_CAFES_PER_DAY',
]

