"""verify_guardrail

Revision ID: db4c64e8931c
Revises: 6d14ff079885
Create Date: 2026-04-03 14:35:52.599261

[비개발자 설명]
이 파일은 DB 구조 변경 이력 하나를 담는 파일입니다.
upgrade() 함수: 변경 사항을 DB에 적용합니다.
downgrade() 함수: 변경 사항을 되돌립니다 (롤백).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# 이 마이그레이션 파일의 고유 ID (자동 생성됨)
revision: str = 'db4c64e8931c'
# 바로 이전 버전의 ID (연결 고리 역할)
down_revision: Union[str, None] = '6d14ff079885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    DB 구조 변경 적용
    → 'alembic upgrade head' 명령 실행 시 이 함수가 호출됩니다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movement_cache', 'is_korea',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_places_rating'), table_name='places')
    op.create_index('idx_places_rating', 'places', ['rating'], unique=False, postgresql_ops={'rating': 'DESC'})
    op.create_index('idx_places_category', 'places', ['category'], unique=False)
    op.alter_column('reservations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.create_index('idx_reservations_status', 'reservations', ['status'], unique=False)
    op.create_index('idx_reservations_user_id', 'reservations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    DB 구조 변경 롤백 (이전 상태로 되돌리기)
    → 'alembic downgrade -1' 명령 실행 시 이 함수가 호출됩니다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reservations_user_id', table_name='reservations')
    op.drop_index('idx_reservations_status', table_name='reservations')
    op.alter_column('reservations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               nullable=True)
    op.drop_index('idx_places_category', table_name='places')
    op.drop_index('idx_places_rating', table_name='places', postgresql_ops={'rating': 'DESC'})
    op.create_index(op.f('idx_places_rating'), 'places', [sa.literal_column('rating DESC')], unique=False)
    op.alter_column('movement_cache', 'is_korea',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    # ### end Alembic commands ###
